language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

install:
  - yarn install

before_script:
  - git clone --branch gh-pages git@${GH_REF} dist

script:
  - make build

after_success:
  - cd dist
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet --force origin gh-pages

env:
  global:
    - GH_REF: github.com:gino20/demonstration-pages.git
