version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-dev
    volumes:
      - .:/app
      - /app/node_modules/
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command:
      - '/bin/bash'
      - '-c'
      - 'NODE_ENV=development ./node_modules/.bin/webpack-dev-server --config ./webpack.config.ts --progress --colors'
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:prod
    volumes:
      - .:/app
    command:
      - '/bin/bash'
      - '-c'
      - 'NODE_ENV=production ./node_modules/.bin/webpack -p --config ./webpack.config.ts'
